default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: fantgeass
  password:

development:
  <<: *default
  database: physician_development

test:
  <<: *default
  database: physician_test

production:
  <<: *default
